=== andrei-heidelbacher/algostorm/algostorm-core/src/main/resources/tileSet.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "image": {
      "type": "object",
      "properties": {
        "resource": {
          "type": "string",
          "pattern": "^res://(/[^/]+)+$"
        },
        "width": {
          "type": "integer",
          "minimum": 1
        },
        "height": {
          "type": "integer",
          "minimum": 1
        }
      },
      "required": [
        "resource",
        "width",
        "height"
      ]
    },
    "tileWidth": {
      "type": "integer",
      "minimum": 1
    },
    "tileHeight": {
      "type": "integer",
      "minimum": 1
    },
    "margin": {
      "type": "integer",
      "minimum": 0
    },
    "spacing": {
      "type": "integer",
      "minimum": 0
    },
    "columns": {
      "type": "integer",
      "minimum": 1
    },
    "tileCount": {
      "type": "integer",
      "minimum": 1
    },
    "animations": {
      "type": "object",
      "patternProperties": {
        ".*": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "tileId": {
                "type": "integer",
                "minimum": 0
              },
              "durationMillis": {
                "type": "integer",
                "minimum": 1
              }
            },
            "required": [
              "tileId",
              "durationMillis"
            ]
          },
          "minItems": 1
        }
      }
    }
  },
  "required": [
    "name",
    "image",
    "tileWidth",
    "tileHeight",
    "margin",
    "spacing",
    "columns",
    "tileCount",
    "animations"
  ]
}

=== andrei-heidelbacher/algostorm/algostorm-core/src/test/resources/tileSet.json
{
  "name":"world",
  "image": {
    "resource": "res:///data.json",
    "width": 288,
    "height": 240
  },
  "tileWidth": 24,
  "tileHeight": 24,
  "margin": 0,
  "spacing": 0,
  "columns": 12,
  "tileCount": 120,
  "animations": {
    "tile:idle": [
      {
        "tileId": 1,
        "durationMillis": 250
      },
      {
        "tileId": 2,
        "durationMillis": 250
      }
    ]
  }
}
